apiVersion: v1
kind: Service
metadata:
  name: flink-ssh-service
  labels:
    app: flink
    role: jobmanager
spec:
  selector:
    app: flink
    role: jobmanager
  ports:
    - port: 22
      name: ssh
