apiVersion: v1
kind: Service
metadata:
  name: flink-web-service
  labels:
    app: flink
    role: jobmanager
spec:
  selector:
    app: flink
    role: jobmanager
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30123
      