apiVersion: v1
kind: Service
metadata:
  name: flink-jm-rpc-service
  labels:
    app: flink
    role: jobmanager
spec:
  clusterIP: None
  selector:
    app: flink
    role: jobmanager
  ports:
    - protocol: TCP
      port: 6123
      targetPort: 6123