apiVersion: v1
kind: PersistentVolume
metadata:
  name: myflk-nfs-pv
  labels:
    storage: myflk-nfs-pv
  annotations:
    kubernetes.io.description: pv-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - vers=4
    - port=2149
  nfs:
    path: /str_jar
    server: 10.10.5.13
  EOF
