apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myflk-nfs-pvc
  labels:
    storage: myflk-nfs-pvc
  annotations:
    kubernetes.io/description: "PersistentVolumeClaim for PV"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
